fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.3.2'
    'wget':
      repo: 'git://github.com/maestrodev/puppet-wget.git'
      ref: '1.5.6'
    'archive':
      repo: 'git://github.com/camptocamp/puppet-archive.git'
      ref: '0.1.3'
  symlinks:
    pentaho: "#{source_dir}"
